define(['underscore','backbone','app/system/buffers','app/views/filelistitem'],function(_,Backbone,Buffers,FileListItem){
	return Backbone.Ribs.View.extend({
		tagName:'ul',
		viewLi:FileListItem,
		collection:null,
		bindings:{
			'el':{
				collection:{
					view:"viewLi",
					col:"collection",
					data:{}
				}
			}
		},
		initialize:function()
		{
			this.collection=Buffers;
		}
	});
});